GET http://localhost:8080/shoppinglist

###

GET http://localhost:8080/shoppinglist/603e198b7a009011340b0d5d

###

POST http://localhost:8080/shoppinglist
Content-Type: application/json

{
    "name": "ShoppingList 1",
    "items": [
        { "name": "Cereal" },
        { "name": "Cheese" },
        { "name": "Beer" }
    ]
}

###

PATCH http://localhost:8080/shoppinglist/603e6bec7b02fa15a501f846
Content-Type: application/json

{
    "items": [
        { "name": "Cereal" },
        { "name": "Cheese" },
        { "name": "Beer" }
    ]
}

###

DELETE http://localhost:8080/shoppinglist/603e5eab11ce2c135d420c68

###

OPTIONS http://localhost:8080/shoppinglist